version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 1
    target-branch: "dev"
    labels:
      - "external-dependency"

  - package-ecosystem: "npm"
    directory: "/components"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 1
    target-branch: "dev"
    labels:
      - "external-dependency"
      
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 1
    target-branch: "dev"
    labels:
      - "external-dependency"      